### ISSUE TITLE
Question about training data

### ISSUE THREAD

**Issue by kkrraa** [rncm-prism/prism-samplernn#24]
Hey I'm new to git and am not sure if this is the right place to ask this.  If it isn't I apologize in advance

I'm trying to figure out the data shape that is used for model fit.  I am using 4 x 6 second audio clips with a batch size of 1 just for testing purposes.  

When I print "train_dataset" in the "main()" function in train.py I get back two shapes: (1, 1088, 1 ) and (1, 1024, 1). 
When I print the individual elements in "train_dataset" using a for loop, it prints out a (1, 200700, 1) in addition to the (1, 1088, 1 ) and (1, 1024, 1)
Which of the shapes is used for the model fit?

I tried printing model.summary() but it didn't give me the input shapes, or specific layer information.  Also tried using model.input_shape and had no luck.  I'm new to all this so it would be really appreciated, and once again sorry if this was the wrong place to post this

Thanks

**Comment by relativeflux** [comment]
@kkrraa Hi, and thanks for your question. So the two shapes (1, 1088, 1 ) and (1, 1024, 1) relate to the sequences that the input audio chunk is split into (1024 is the default sequence length). The network needs a target sequence, which is what it tries to predict. The sequences overlap, which is why the target is 1088 - that's 1024 + 64 (64 is the frame size of the first RNN tier). So at each training step it takes a sequence of 1088 samples, and then iterates forward 1024 samples. In fact the input audio chunk has 64 samples of silence added at the start, so the overlapping sequences fit the entire audio chunk.

What exactly is the size of your audio chunks? The 200700 is likely the size of the individual chunk, in samples. If your sr = 20050 you'll have 200500 per chunk. I usually work at sr = 16000 (the default) which, with a frame size of 64 and a chunk size of 8 seconds = 128064 samples. What frame size(s) are you using?

N.B: By frame size(s) I mean the sizes of the sample frames processed by each RNN tier, by default = 64 and 16.

**Comment by relativeflux** [comment]
There are good explanations of the SampleRNN architecture in the following:

https://www.duo.uio.no/bitstream/handle/10852/63734/thesis-160518-03.pdf
https://upcommons.upc.edu/bitstream/handle/2117/117980/GeorginaDorca_Final_Report.pdf?sequence=1&isAllowed=y

The latter has a very detailed explanation of SampleRNN in Chapter 3, along with some helpful illustrations.

**Comment by kkrraa** [comment]
Hey thanks so much for the detailed response, I read the papers and tried to understand as much as I could.  I'm using a frame size of 64, and a chunk size of around 6 seconds at 44100 SR.  I should definitely start working in 16000, it just hit me that the training is probably wasting resources trying to learn patterns in the super high frequencies.  

I want to try and create an extremely simple model using Keras that can accept training data formatted in the shape of the "train_dataset" variable that is fed to model.fit in the train script.  What is the easiest way I could set something like that up, in regards to creating a model who's input shape would accept this data type

Thanks for your help

**Comment by kkrraa** [comment]
Thank you very much
